apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-cloud
  namespace: default
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: hello-cloud
  template:
    metadata:
      labels:
        app: hello-cloud
    spec:
      containers:
        - name: hello-cloud
          image: mandlon/hello-cloud:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
